
version: "3.9"
services:
  server:
    build: 
      context: ./build
      dockerfile: Dockerfile.Apache
    ports:
      - "8080:80"
    volumes:
      - ./frontend/css:/usr/local/apache2/htdocs/css/
      - ./frontend/html:/usr/local/apache2/htdocs/html/
      - ./frontend/images:/usr/local/apache2/htdocs/html/
      - ./frontend/js:/usr/local/apache2/htdocs/js/
      - ./frontend/index.html:/usr/local/apache2/htdocs/index.html
  backend:
    build:
      context: ./build
      dockerfile: Dockerfile.Backend
    ports:
      - "5001:5001"
    depends_on:
      - db
    volumes:
      - ./backend:/home/project/backend/
  db:
    image: postgres:alpine3.16
    ports: 
      - "5432:5432"
    volumes:
      - dbtest:/var/lib/postgresql/data
      - ./build/createDB.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_PASSWORD=mnpwd
volumes:
  dbtest:
