
version: "3.9"
services:
  server:
    build: 
      context: .
      dockerfile: Apache
    ports:
      - "8080:80"
  backend:
    build:
      context: .
      dockerfile: Backend
    ports:
      - "5001:5001"
    depends_on:
      - db
  db:
    image: postgres:alpine3.16
    ports: 
      - "5432:5432"
    volumes:
      - dbtest:/var/lib/postgresql/data
      - ./createDB.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_PASSWORD=mnpwd
volumes:
  dbtest:
